name: Start game on issue
on:
  issues:
    types: [opened]

jobs:
  startGame:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Generate semi-random number from issue
        run: echo "$EVENT_ID % $(cat words.txt | wc -l)" | bc
        env:
          EVENT_ID: ${{ github.event.issue.id }}
