name: Start game on issue
on:
  issues:
    types: [opened]

jobs:
  startGame:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Generate semi-random number from issue
        run: |
          LINE=$(echo "$EVENT_ID % $(cat words.txt | wc -l)" | bc)
          head -n $LINE words.txt | tail -n 1
        env:
          EVENT_ID: ${{ github.event.issue.id }}
