name: Start game on issue
on:
  issues:
    types: [opened]

jobs:
  startGame:
    runs-on: ubuntu-latest
    steps:
      - name: Generate semi-random number from issue
        run: echo $EVENT_ID
        env:
          EVENT_ID: ${{ toJSON(github.event) }}
